default: &default
  adapter: postgresql
  encoding: unicode
  # Docker development env
  # host: 192.168.99.100
  # Heroku development prev
  host: localhost
  username: postgres
  # Docker password
  # password: docker
  # Heroku password
  password: 
  pool: 5

development:
  <<: *default
  database: rails_transactions_development

test:
  <<: *default
  database: rails_transactions_test